package com.inventorymanagement;

import com.inventorymanagement.dto.request.*;
import com.inventorymanagement.dto.response.*;
import com.inventorymanagement.model.enums.Category;
import com.inventorymanagement.model.enums.MovementType;
import com.inventorymanagement.model.enums.POStatus;
import com.inventorymanagement.service.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;					
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;

import static org.assertj.core.api.Assertions.*;

@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
class InventoryManagementApplicationTests {

    @Autowired AuthService authService;
    @Autowired ProductService productService;
    @Autowired StockService stockService;
    @Autowired PurchaseOrderService purchaseOrderService;
    @Autowired SupplierService supplierService;
    @Autowired DashboardService dashboardService;

    static Integer supplierId;
    static Integer groceryProductId;
    static Integer electronicsProductId;
    static Integer poId;
    static String userToken;

    @Test @Order(1)
    void TC01_contextLoads() {
        assertThat(authService).isNotNull();
        assertThat(productService).isNotNull();
        assertThat(stockService).isNotNull();
        assertThat(purchaseOrderService).isNotNull();
        assertThat(supplierService).isNotNull();
        assertThat(dashboardService).isNotNull();
    }

    @Test @Order(2)
    void TC02_registerUser_success() {
        RegisterRequest request = new RegisterRequest();
        request.setEmail("priya@inventory.com");
        request.setPassword("Pass@1234");
        request.setFullName("Priya Sharma");
        request.setRole("store_manager");
        AuthResponse response = authService.register(request);
        assertThat(response.getToken()).isNotBlank();
        assertThat(response.getEmail()).isEqualTo("priya@inventory.com");
        userToken = response.getToken();
    }

    @Test @Order(3)
    void TC03_registerDuplicateEmail_throws() {
        RegisterRequest request = new RegisterRequest();
        request.setEmail("priya@inventory.com");
        request.setPassword("Pass@1234");
        request.setFullName("Duplicate User");
        assertThatThrownBy(() -> authService.register(request)).isInstanceOf(IllegalArgumentException.class);
    }

    @Test @Order(4)
    void TC04_loginUser_success() {
        LoginRequest request = new LoginRequest();
        request.setEmail("priya@inventory.com");
        request.setPassword("Pass@1234");
        AuthResponse response = authService.login(request);
        assertThat(response.getToken()).isNotBlank();
    }

    @Test @Order(5)
    void TC05_createSupplier_success() {
        SupplierRequest request = new SupplierRequest();
        request.setName("FreshMart Distributors");
        request.setSupplierCode("SUP-0001");
        request.setContactEmail("supply@freshmart.com");
        request.setPaymentTermsDays(30);
        request.setLeadTimeDays(5);
        SupplierResponse response = supplierService.createSupplier(request);
        assertThat(response.getId()).isNotNull();
        supplierId = response.getId();
    }

    @Test @Order(6)
    void TC06_createDuplicateSupplier_throws() {
        SupplierRequest request = new SupplierRequest();
        request.setName("Duplicate Supplier");
        request.setSupplierCode("SUP-0001");
        assertThatThrownBy(() -> supplierService.createSupplier(request)).isInstanceOf(IllegalArgumentException.class);
    }

    @Test @Order(7)
    void TC07_createGroceryProduct_skuAutoGenerated() {
        ProductRequest request = new ProductRequest();
        request.setName("Basmati Rice 5kg");
        request.setCategory(Category.grocery);
        request.setUnitPrice(450.0);
        request.setCostPrice(380.0);
        request.setUnitOfMeasure("kg");
        request.setReorderPoint(20);
        request.setReorderQuantity(100);
        request.setSupplierId(supplierId);
        request.setInitialStock(50);
        ProductResponse response = productService.createProduct(request);
        assertThat(response.getSku()).matches("SKU-GRO-\\d{4}");
        assertThat(response.getStockLevel().getQuantityOnHand()).isEqualTo(50);
        groceryProductId = response.getId();
    }

    @Test @Order(8)
    void TC08_createElectronicsProduct_elcSkuPrefix() {
        ProductRequest request = new ProductRequest();
        request.setName("USB-C Charger");
        request.setCategory(Category.electronics);
        request.setUnitPrice(999.0);
        request.setCostPrice(700.0);
        request.setReorderPoint(5);
        request.setReorderQuantity(20);
        request.setInitialStock(15);
        ProductResponse response = productService.createProduct(request);
        assertThat(response.getSku()).matches("SKU-ELC-\\d{4}");
        electronicsProductId = response.getId();
    }

    @Test @Order(9)
    void TC09_listAllProducts_returnsAll() {
        List<ProductResponse> products = productService.getAllProducts(null, null);
        assertThat(products).hasSizeGreaterThanOrEqualTo(2);
    }

    @Test @Order(10)
    void TC10_listProductsByCategory_filtered() {
        List<ProductResponse> products = productService.getAllProducts(Category.grocery, null);
        assertThat(products)
            .isNotEmpty()
            .allMatch(p -> p.getCategory() == Category.grocery);
    }

    @Test @Order(11)
    void TC11_getProductById_includesStockAndMovements() {
        ProductResponse response = productService.getProductById(groceryProductId);
        assertThat(response)
            .extracting(ProductResponse::getStockLevel, ProductResponse::getRecentMovements)
            .doesNotContainNull();
    }

    @Test @Order(12)
    void TC12_updateStock_movementRecordedAndQtyUpdated() {
        StockUpdateRequest request = new StockUpdateRequest();
        request.setMovementType(MovementType.sale);
        request.setQuantity(-10);
        request.setNotes("Sale to customer");
        request.setRecordedBy("Dev Kumar");
        ProductResponse response = stockService.updateStock(groceryProductId, request);
        assertThat(response.getStockLevel().getQuantityOnHand()).isEqualTo(40);
    }

    @Test @Order(13)
    void TC13_stockBelowReorderPoint_alertCreated() {
        StockUpdateRequest request = new StockUpdateRequest();
        request.setMovementType(MovementType.sale);
        request.setQuantity(-25);
        request.setNotes("Bulk sale");
        request.setRecordedBy("Dev Kumar");
        stockService.updateStock(groceryProductId, request);
        List<StockAlertResponse> alerts = stockService.getLowStockAlerts();
        assertThat(alerts)
            .isNotEmpty()
            .anyMatch(a -> a.getProductId().equals(groceryProductId) && a.getAlertType().equals("low_stock"));
    }

    @Test @Order(14)
    void TC14_stockReachesZero_outOfStockAlertCreated() {
        StockUpdateRequest request = new StockUpdateRequest();
        request.setMovementType(MovementType.sale);
        request.setQuantity(-15);
        request.setNotes("Clearance sale");
        request.setRecordedBy("Dev Kumar");
        stockService.updateStock(groceryProductId, request);
        List<StockAlertResponse> alerts = stockService.getLowStockAlerts();
        assertThat(alerts).anyMatch(a -> a.getProductId().equals(groceryProductId) && a.getAlertType().equals("out_of_stock"));
    }

    @Test @Order(15)
    void TC15_lowStockFilter_returnsLowStockProducts() {
        List<ProductResponse> products = productService.getAllProducts(null, true);
        assertThat(products)
            .isNotEmpty()
            .allMatch(p -> p.getStockLevel().getQuantityAvailable() <= p.getReorderPoint());
    }

    @Test @Order(16)
    void TC16_createPurchaseOrder_poNumberAutoGenerated() {
        PurchaseOrderRequest request = new PurchaseOrderRequest();
        request.setSupplierId(supplierId);
        POItemRequest item = new POItemRequest();
        item.setProductId(groceryProductId);
        item.setQuantityOrdered(100);
        item.setUnitCost(380.0);
        request.setItems(List.of(item));
        PurchaseOrderResponse response = purchaseOrderService.createPurchaseOrder(request);
        assertThat(response.getPoNumber()).matches("PO-\\d{4}-\\d{4}");
        assertThat(response.getStatus()).isEqualTo(POStatus.draft);
        poId = response.getId();
    }

    @Test @Order(17)
    void TC17_listAllOrders_returnsOrders() {
        List<PurchaseOrderResponse> orders = purchaseOrderService.getAllOrders(null, null);
        assertThat(orders).isNotEmpty();
    }

    @Test @Order(18)
    void TC18_listOrdersByStatus_filtered() {
        List<PurchaseOrderResponse> drafts = purchaseOrderService.getAllOrders(POStatus.draft, null);
        assertThat(drafts)
            .isNotEmpty()
            .allMatch(o -> o.getStatus() == POStatus.draft);
    }

    @Test @Order(19)
    void TC19_getOrderById_returnsWithItems() {
        PurchaseOrderResponse response = purchaseOrderService.getOrderById(poId);
        assertThat(response.getItems()).hasSize(1);
    }

    @Test @Order(20)
    void TC20_receivePurchaseOrder_stockUpdatedAndAlertResolved() {
        PurchaseOrderResponse submitted = purchaseOrderService.submitPurchaseOrder(poId);
        assertThat(submitted.getStatus()).isEqualTo(POStatus.submitted);
        PurchaseOrderResponse approved = purchaseOrderService.approvePurchaseOrder(poId);
        assertThat(approved.getStatus()).isEqualTo(POStatus.acknowledged);
        PurchaseOrderResponse response = purchaseOrderService.receivePurchaseOrder(poId);
        assertThat(response.getStatus()).isEqualTo(POStatus.received);
        assertThat(productService.getProductById(groceryProductId).getStockLevel().getQuantityOnHand()).isEqualTo(100);
    }

    @Test @Order(21)
    void TC21_supplierCatalog_returnsSupplierProducts() {
        SupplierCatalogResponse catalog = supplierService.getSupplierCatalog(supplierId);
        assertThat(catalog.getSupplierId()).isEqualTo(supplierId);
        assertThat(catalog.getProducts()).isNotEmpty();
    }

    @Test @Order(22)
    void TC22_dashboard_returnsMetrics() {
        DashboardResponse dashboard = dashboardService.getDashboard();
        assertThat(dashboard.getTotalProducts()).isGreaterThan(0);
        assertThat(dashboard.getTotalStockValue()).isGreaterThan(0.0);
    }

    @Test @Order(23)
    void TC23_getMissingProduct_throws() {
        assertThatThrownBy(() -> productService.getProductById(999999))
                .isInstanceOf(ResponseStatusException.class);
    }

    @Test @Order(24)
    void TC24_receiveAlreadyReceivedPO_throws() {
        assertThatThrownBy(() -> purchaseOrderService.receivePurchaseOrder(poId))
                .isInstanceOf(ResponseStatusException.class);
    }

    @Test @Order(25)
    void TC25_dashboardStockValuePositive() {
        assertThat(dashboardService.getDashboard().getTotalStockValue()).isPositive();
    }
}
